[build-system]
requires = ["setuptools>=65.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "inputkit"
version = "0.1.0"
description = "Simple and cross-platform terminal input with reusable validators."
readme = "README.md"
requires-python = ">=3.8"
license = { text = "MIT" }
authors = [
    { name = "Mohammad Khazaei", email = "mkhazaei.dev@gmail.com" }
]
keywords = ["CLI", "input", "validators", "terminal", "python"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Operating System :: OS Independent",
    "License :: OSI Approved :: MIT License"
]
dependencies = []

[project.urls]
Homepage = "https://github.com/mkhazaeidev/inputkit"
Documentation = "https://github.com/mkhazaeidev/inputkit/docs"
Repository = "https://github.com/mkhazaeidev/inputkit"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.dev-dependencies]
pytest = "^7.0"
black = "^23.0"
mypy = "^1.0"
